#!/bin/bash

# Move all drafts into the drafts folder
for filename in content/drafts/*; do
	if grep -q "draft: false" $filename; then
		echo "Moving draft to posts"
		mv $filename content/posts
		echo
	else
		echo "No drafts to move."
		echo
	fi
done

# Check for changes
DIFF=$(diff content/posts/ ~/Documents/writings/nyxus/posts/)

# Copy the everything into the writings repository if there were changes
if ["$DIFF" = ""]; then
	echo "Nothing to copy to writings repository"
	echo
else
	echo "Moving posts to the writings repository..."
	rsync -avz --delete content/posts ~/Documents/writings/nyxus
	git -C ~/Documents/writings add .
	echo "Add a git commit: "
	read commesg1
	git -C ~/Documents/writings commit -m "$commesg1"
	git -C ~/Documents/writings push -u origin master
fi

# Make changes to live site
echo "Are you ready to publish? y/n"
read answer
echo

# If yes then commit to site repo
if [ "$answer" = "y" ] || [ "$answer" = "Y" ] ; then
	hugo
	git add .
	echo "Add a git commit: "
	read commesg
	echo
	git commit -m "$commesg"
	git push -u origin master

# Else exit
elif [ "$answer" = "n" ] || [ "$answer" = "N" ]; then
	echo "Exiting now!"
	echo
	exit 1
else
	echo "Please enter a valid answer."
fi
